// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6329.UglyBuckling.subsystems;

import org.usfirst.frc6329.UglyBuckling.RobotMap;
import org.usfirst.frc6329.UglyBuckling.commands.*;

import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Winch extends Subsystem {

    private final SpeedController winchESC = RobotMap.winchWinchESC;

    public void initDefaultCommand() {

        setDefaultCommand(new StopWinch());
        
    }
    
    public void beginWinch(double slider) {
    	if(slider > 0) {  				// Forward Winch
    		winchESC.set(slider);
    	}
    }
    
    public void stop() {
    	winchESC.set(0);	
    }

}
