// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6329.UglyBuckling.commands.autonomous;

import edu.wpi.first.wpilibj.command.CommandGroup;

import org.usfirst.frc6329.UglyBuckling.Robot;
import org.usfirst.frc6329.UglyBuckling.commands.moveGear.EjectGear;
import org.usfirst.frc6329.UglyBuckling.commands.moveGear.HoldGearDown;
import org.usfirst.frc6329.UglyBuckling.commands.moveGear.LowerGear;
import org.usfirst.frc6329.UglyBuckling.commands.moveGear.StoreGear;

/**
 *
 */
public class Red1 extends CommandGroup {

    public Red1() {

    	requires(Robot.driveSystem);

    	addParallel(new StoreGear());
    	addSequential(new DriveStraight(0.7,2.8));
    	addSequential(new DriveStraight(0,0.5));
    	addSequential(new TurnToAngle(.6, 55));
    	//addParallel( new LowerGear());
    	//addSequential(new DriveStraight(0,1));
    	//addParallel(new HoldGearDown());
    	addSequential(new DriveStraight(0,0.5)); // Delete if vision in use
    	//addSequential(new VisionAlign(.5,3));
    	//addParallel(new StoreGear());
    	//addSequential(new DriveStraight(0,1));
    	addSequential(new DriveStraight(0.7,3.3));
    	addSequential(new DriveStraight(0.5,1));
    	addSequential(new DriveStraight(0,0.5));
    	addParallel(new EjectGear());
    	addSequential(new DriveStraight(0,1));
    	addParallel(new HoldGearDown());
    	addSequential(new DriveStraight(-.7,2));
    	addParallel(new StoreGear());
    	addSequential(new DriveStraight(0,1));
    } 
}
