// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6329.UglyBuckling.commands.moveGear;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc6329.UglyBuckling.Constants;
import org.usfirst.frc6329.UglyBuckling.Robot;
/**
 *
 */
public class MoveTheCrane extends Command {

    private long clearMillis;
    private long endMillis;
    private final long time;
    private final double speed;
	
    public MoveTheCrane(long time, double speed) {
    	requires(Robot.gearCrane);
    	this.time = time;
    	this.speed = speed;
    }

    @Override
    protected void initialize() {
    	clearMillis = System.currentTimeMillis() + 250;
    	endMillis = time==0 ? 0 : System.currentTimeMillis() + time;
    }

    @Override
    protected void execute() {
    	Robot.gearCrane.gearCraneGearCraneESC.set(speed);
    }

    @Override
    protected boolean isFinished() {
    	return (endMillis > 0 && System.currentTimeMillis() > endMillis) || Robot.pdp.getGearCraneAmps() > Constants.GearSystem.HARDSTOP_AMPS;

    }

    @Override
    protected void end() {
    	Robot.gearCrane.StopTheCrane();
    }

    @Override
    protected void interrupted() {
    	end();
    }
}
